# goal definition
int32 goal
int32 vision_task_type
string template_name_2d
string calib_pos_name_eih_2d
string calib_pos_name_eth_2d
string calib_cam_name_eih
string calib_cam_name_eth
string track_target_name_2d
string track_target_name_3d
string PCB_template_name
sensor_msgs/Image image_to_process # this is the image to be processed
sensor_msgs/PointCloud2 pointcloud_to_process # this is the point cloud to be processed
string image_path
string image_name
string cam_parameter_path
string eih_calib_result_path
string eih_calib_tool_pose_path
---
# result definition
bool intrinsics_calibrated
# for wifi2021 project only, not general purpose messages
# pick up from the board array
int32 number_of_tracked_object

#pcba
geometry_msgs/Point[] PCB_center
geometry_msgs/Point[] PCB_rotation
geometry_msgs/Point uv_center

# eye in hand calibration result
geometry_msgs/Pose eih_calib_result
---
# feedback
int32 data